// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedbackToolDissertation.Data.FeedbackToolDissertation
{
    public partial class Feedback
    {
        public int Id { get; set; }
        public string Feedback1 { get; set; }
        public int Grade { get; set; }
        public string Section { get; set; }
        public string Module { get; set; }
        public string UserName { get; set; }
    }
}