// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;


namespace FeedbackToolDissertation.Data.FeedbackToolDissertation
{
    public partial class Modules
    {
        public int Id { get; set; }

        [Required]
        public string ModuleName { get; set; }
        public string UserName { get; set; }
    }
}