// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FeedbackToolDissertation.Data.FeedbackToolDissertation
{
    public partial class Sections
    {
        public int Id { get; set; }
        public string SectionName { get; set; }
        public string Acwname { get; set; }
        public string ModuleName { get; set; }
        public string UserName { get; set; }
    }
}